apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 0.7
              memory: "0.7Gi"
            requests:
              cpu: 0.2
              memory: "0.2Gi"
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USERNAME
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - exec pg_isready -U postgres
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - exec pg_isready -U postgres
            initialDelaySeconds: 30
            timeoutSeconds: 5
