apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  namespace: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: dipesh017/demo:result
        resources:
          limits:
            cpu: 0.7
            memory: "0.7Gi"
          requests:
            cpu: 0.2
            memory: "0.2Gi"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
