apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: dipesh017/demo:worker
          resources:
            limits:
              cpu: 0.7
              memory: "0.7Gi"
            requests:
              cpu: 0.2
              memory: "0.2Gi"
