apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: local
spec:
  selector:
    app: worker
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
